
apiVersion: v1
kind: Namespace
metadata:
  name: gitops
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-k8s-app
  namespace: gitops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/your-repo/your-k8s-app.git
    targetRevision: HEAD
    path: ./k8s
  project: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-system
  namespace: gitops
data:
  install.yaml: |
    apiVersion: source.toolkit.fluxcd.io/v1beta2
    kind: GitRepository
    metadata:
      name: flux-system
      namespace: flux-system
    spec:
      interval: 1m0s
      url: https://github.com/your-repo/your-flux-config.git
