
apiVersion: v2
name: my-k8s-app
description: A Helm chart for deploying a secure application to Kubernetes
version: 0.1.0
appVersion: 1.0.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-k8s-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-k8s-app
  template:
    metadata:
      labels:
        app: my-k8s-app
    spec:
      containers:
      - name: my-k8s-app
        image: nginx:stable
